version: "2.17.3"

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./env/dev.env
    ports:
      - ${DB_PORT}:${DB_PORT}

  node-app:
    build:
      context: .
      target: development

    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./env/dev.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - CREDIT_CARD_API_HOST=${CREDIT_CARD_API_HOST}
    ports:
      - ${PORT}:${PORT}
