version: "2.17.3"

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./env/prod.env
    ports:
      - ${DB_PORT}:${DB_PORT}

  node-app:
    build:
      context: .
      target: production

    env_file:
      - ./env/prod.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - CREDIT_CARD_API_HOST=${CREDIT_CARD_API_HOST}
    ports:
      - ${PORT}:${PORT}
